//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalkMessaging
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "btsmsgdsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"BizTalkMessaging";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID BizTalkMessagingDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BizTalkMessagingCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID BizTalkMessagingExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BizTalkMessagingCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewBizTalkMessagingExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BizTalkMessagingCommandSetId), 0x0001);
	
		// Package identifier
		public const string BizTalkMessagingPackageId = "9204b2f6-ddc7-4163-9609-02e626156d2d";
		
		// Editor factory identifier
		public const string BizTalkMessagingEditorFactoryId = "85b44b4b-4011-447b-a0e6-56a673c497e2";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string BizTalkMessagingModelExplorerToolWindowId = "4141f16f-2bd8-41ea-86de-0991c2ed0354";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace BizTalkMessaging
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string BizTalkMessagingCommandSetId = "f3f3e6e4-8bd5-43e9-9229-f18173416bca";
	}
}