//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;


namespace BizTalkMessaging
{
	/// <summary>
	/// DomainModel BizTalkMessagingDomainModel
	/// Description for BizTalkMessaging.BizTalkMessaging
	/// </summary>
	[DslDesign::DisplayNameResource("BizTalkMessaging.BizTalkMessagingDomainModel.DisplayName", typeof(global::BizTalkMessaging.BizTalkMessagingDomainModel), "BizTalkMessaging.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("BizTalkMessaging.BizTalkMessagingDomainModel.Description", typeof(global::BizTalkMessaging.BizTalkMessagingDomainModel), "BizTalkMessaging.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("4d0412b7-4396-4ceb-a2cf-263a5cbeb971")]
	public partial class BizTalkMessagingDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// BizTalkMessagingDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x4d0412b7, 0x4396, 0x4ceb, 0xa2, 0xcf, 0x26, 0x3a, 0x5c, 0xbe, 0xb9, 0x71);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public BizTalkMessagingDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
		}
		
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(BizTalkMessagingModel),
				typeof(Application),
				typeof(OutPort),
				typeof(InPort),
				typeof(Broker),
				typeof(BizTalkMessagingModelHasApplications),
				typeof(BizTalkMessagingModelHasBroker),
				typeof(BrokerHasOutPorts),
				typeof(BrokerHasInPorts),
				typeof(ApplicationSendsToInPort),
				typeof(OutPortSendsToApplication),
				typeof(BizTalkMessagingDiagram),
				typeof(ConnectionApplication_InPort),
				typeof(ConnectionOutPort_Application),
				typeof(ApplicationShape),
				typeof(BrokerShape),
				typeof(OutPortShape),
				typeof(InPortShape),
				typeof(global::BizTalkMessaging.FixUpDiagram),
				typeof(global::BizTalkMessaging.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Application), "Name", Application.NameDomainPropertyId, typeof(Application.NamePropertyHandler)),
				new DomainMemberInfo(typeof(InPort), "Message", InPort.MessageDomainPropertyId, typeof(InPort.MessagePropertyHandler)),
				new DomainMemberInfo(typeof(InPort), "Protocol", InPort.ProtocolDomainPropertyId, typeof(InPort.ProtocolPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(BizTalkMessagingModelHasApplications), "BizTalkMessagingModel", BizTalkMessagingModelHasApplications.BizTalkMessagingModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(BizTalkMessagingModelHasApplications), "Element", BizTalkMessagingModelHasApplications.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(BizTalkMessagingModelHasBroker), "BizTalkMessagingModel", BizTalkMessagingModelHasBroker.BizTalkMessagingModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(BizTalkMessagingModelHasBroker), "Broker", BizTalkMessagingModelHasBroker.BrokerDomainRoleId),
				new DomainRolePlayerInfo(typeof(BrokerHasOutPorts), "Broker", BrokerHasOutPorts.BrokerDomainRoleId),
				new DomainRolePlayerInfo(typeof(BrokerHasOutPorts), "OutPort", BrokerHasOutPorts.OutPortDomainRoleId),
				new DomainRolePlayerInfo(typeof(BrokerHasInPorts), "Broker", BrokerHasInPorts.BrokerDomainRoleId),
				new DomainRolePlayerInfo(typeof(BrokerHasInPorts), "InPort", BrokerHasInPorts.InPortDomainRoleId),
				new DomainRolePlayerInfo(typeof(ApplicationSendsToInPort), "Application", ApplicationSendsToInPort.ApplicationDomainRoleId),
				new DomainRolePlayerInfo(typeof(ApplicationSendsToInPort), "InPort", ApplicationSendsToInPort.InPortDomainRoleId),
				new DomainRolePlayerInfo(typeof(OutPortSendsToApplication), "OutPort", OutPortSendsToApplication.OutPortDomainRoleId),
				new DomainRolePlayerInfo(typeof(OutPortSendsToApplication), "Application", OutPortSendsToApplication.ApplicationDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(12);
				createElementMap.Add(typeof(BizTalkMessagingModel), 0);
				createElementMap.Add(typeof(Application), 1);
				createElementMap.Add(typeof(OutPort), 2);
				createElementMap.Add(typeof(InPort), 3);
				createElementMap.Add(typeof(Broker), 4);
				createElementMap.Add(typeof(BizTalkMessagingDiagram), 5);
				createElementMap.Add(typeof(ConnectionApplication_InPort), 6);
				createElementMap.Add(typeof(ConnectionOutPort_Application), 7);
				createElementMap.Add(typeof(ApplicationShape), 8);
				createElementMap.Add(typeof(BrokerShape), 9);
				createElementMap.Add(typeof(OutPortShape), 10);
				createElementMap.Add(typeof(InPortShape), 11);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::BizTalkMessaging.BizTalkMessagingDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new BizTalkMessagingModel(partition, propertyAssignments);
				case 1: return new Application(partition, propertyAssignments);
				case 2: return new OutPort(partition, propertyAssignments);
				case 3: return new InPort(partition, propertyAssignments);
				case 4: return new Broker(partition, propertyAssignments);
				case 5: return new BizTalkMessagingDiagram(partition, propertyAssignments);
				case 6: return new ConnectionApplication_InPort(partition, propertyAssignments);
				case 7: return new ConnectionOutPort_Application(partition, propertyAssignments);
				case 8: return new ApplicationShape(partition, propertyAssignments);
				case 9: return new BrokerShape(partition, propertyAssignments);
				case 10: return new OutPortShape(partition, propertyAssignments);
				case 11: return new InPortShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(6);
				createElementLinkMap.Add(typeof(BizTalkMessagingModelHasApplications), 0);
				createElementLinkMap.Add(typeof(BizTalkMessagingModelHasBroker), 1);
				createElementLinkMap.Add(typeof(BrokerHasOutPorts), 2);
				createElementLinkMap.Add(typeof(BrokerHasInPorts), 3);
				createElementLinkMap.Add(typeof(ApplicationSendsToInPort), 4);
				createElementLinkMap.Add(typeof(OutPortSendsToApplication), 5);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::BizTalkMessaging.BizTalkMessagingDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new BizTalkMessagingModelHasApplications(partition, roleAssignments, propertyAssignments);
				case 1: return new BizTalkMessagingModelHasBroker(partition, roleAssignments, propertyAssignments);
				case 2: return new BrokerHasOutPorts(partition, roleAssignments, propertyAssignments);
				case 3: return new BrokerHasInPorts(partition, roleAssignments, propertyAssignments);
				case 4: return new ApplicationSendsToInPort(partition, roleAssignments, propertyAssignments);
				case 5: return new OutPortSendsToApplication(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "BizTalkMessaging.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return BizTalkMessagingDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (BizTalkMessagingDomainModel.resourceManager == null)
				{
					BizTalkMessagingDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(BizTalkMessagingDomainModel).Assembly);
				}
				return BizTalkMessagingDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return BizTalkMessagingDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return BizTalkMessagingDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (BizTalkMessagingDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new BizTalkMessagingCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					BizTalkMessagingDomainModel.copyClosure = copyFilter;
				}
				return BizTalkMessagingDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (BizTalkMessagingDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new BizTalkMessagingDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					BizTalkMessagingDomainModel.removeClosure = removeFilter;
				}
				return BizTalkMessagingDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::BizTalkMessaging.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::BizTalkMessaging.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::BizTalkMessaging.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::BizTalkMessaging.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class BizTalkMessagingDeleteClosure : BizTalkMessagingDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public BizTalkMessagingDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	public partial class BizTalkMessagingDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public BizTalkMessagingDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::BizTalkMessaging.BizTalkMessagingModelHasApplications.ElementDomainRoleId, true);
			DomainRoles.Add(global::BizTalkMessaging.BizTalkMessagingModelHasBroker.BrokerDomainRoleId, true);
			DomainRoles.Add(global::BizTalkMessaging.BrokerHasOutPorts.OutPortDomainRoleId, true);
			DomainRoles.Add(global::BizTalkMessaging.BrokerHasInPorts.InPortDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class BizTalkMessagingCopyClosure : BizTalkMessagingCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public BizTalkMessagingCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	public partial class BizTalkMessagingCopyClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public BizTalkMessagingCopyClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::BizTalkMessaging.BizTalkMessagingModelHasBroker.BrokerDomainRoleId, true);
			DomainRoles.Add(global::BizTalkMessaging.BrokerHasOutPorts.OutPortDomainRoleId, true);
			DomainRoles.Add(global::BizTalkMessaging.BrokerHasInPorts.InPortDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			if (sourceRoleInfo == null) throw new global::System.ArgumentNullException("sourceRoleInfo");
			return this.DomainRoles.Contains(sourceRoleInfo.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	#endregion
		
}
namespace BizTalkMessaging
{
	/// <summary>
	/// DomainEnumeration: Protocol
	/// Description for BizTalkMessaging.Protocol
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Protocol
	{
		/// <summary>
		/// FILE
		/// Description for BizTalkMessaging.Protocol.FILE
		/// </summary>
		[DslDesign::DescriptionResource("BizTalkMessaging.Protocol/FILE.Description", typeof(global::BizTalkMessaging.BizTalkMessagingDomainModel), "BizTalkMessaging.GeneratedCode.DomainModelResx")]
		FILE,
		/// <summary>
		/// HTTP
		/// Description for BizTalkMessaging.Protocol.HTTP
		/// </summary>
		[DslDesign::DescriptionResource("BizTalkMessaging.Protocol/HTTP.Description", typeof(global::BizTalkMessaging.BizTalkMessagingDomainModel), "BizTalkMessaging.GeneratedCode.DomainModelResx")]
		HTTP,
	}
}

