//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace BizTalkMessaging
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class BizTalkMessagingToolboxHelper : BizTalkMessagingToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new BizTalkMessagingToolboxHelper.
		/// </summary>
		public BizTalkMessagingToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	public abstract class BizTalkMessagingToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify BizTalkMessaging toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "BizTalkMessaging.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Application_To_Broker_Connector connector tool.
		/// </summary>
		public const string Application_To_Broker_ConnectorFilterString = "Application_To_Broker_Connector.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Broker_To_Application_Connector connector tool.
		/// </summary>
		public const string Broker_To_Application_ConnectorFilterString = "Broker_To_Application_Connector.1.0";

		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new BizTalkMessagingToolboxHelperBase.
		/// </summary>
		protected BizTalkMessagingToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::BizTalkMessaging.BizTalkMessagingDomainModel.SingletonResourceManager.GetString("BizTalkMessagingToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 6;
			}
		}
		

		/// <summary>
		/// Returns a list of toolbox items for use with this DSL.
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			
			// Create store and load domain models.
			using(DslModeling::Store store = new DslModeling::Store(this.ServiceProvider))
			{
				store.LoadDomainModels(typeof(DslDiagrams::CoreDesignSurfaceDomainModel),
					typeof(global::BizTalkMessaging.BizTalkMessagingDomainModel));
				global::System.Resources.ResourceManager resourceManager = global::BizTalkMessaging.BizTalkMessagingDomainModel.SingletonResourceManager;
				global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			
				// Open transaction so we can create model elements corresponding to toolbox items.
				using(DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{

					// Add Broker shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"BrokerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("BrokerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("BrokerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"BizTalkMessagingToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("BizTalkMessagingToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Broker", // F1 help keyword for the toolbox item.
						resourceManager.GetString("BrokerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::BizTalkMessaging.Broker.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add InPort shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"InPortToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InPortToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InPortToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"BizTalkMessagingToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("BizTalkMessagingToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"InPort", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InPortToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::BizTalkMessaging.InPort.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Outport shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"OutportToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OutportToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OutportToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"BizTalkMessagingToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("BizTalkMessagingToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Outport", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OutportToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::BizTalkMessaging.OutPort.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Application shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ApplicationToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ApplicationToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ApplicationToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"BizTalkMessagingToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("BizTalkMessagingToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CreateExampleClassF1Keyword", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ApplicationToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::BizTalkMessaging.Application.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Application_To_Broker_Connector connector tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"Application_To_Broker_ConnectorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("Application_To_Broker_ConnectorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("Application_To_Broker_ConnectorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"BizTalkMessagingToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("BizTalkMessagingToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ApplicationToBrokerConnector", // F1 help keyword for the toolbox item.
						resourceManager.GetString("Application_To_Broker_ConnectorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(Application_To_Broker_ConnectorFilterString)
						}));

					// Add Broker_To_Application_Connector connector tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"Broker_To_Application_ConnectorToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("Broker_To_Application_ConnectorToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("Broker_To_Application_ConnectorToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"BizTalkMessagingToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("BizTalkMessagingToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Broker_To_Application_Connector", // F1 help keyword for the toolbox item.
						resourceManager.GetString("Broker_To_Application_ConnectorToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(Broker_To_Application_ConnectorFilterString)
						}));

					t.Rollback();
				}
			}

			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}
	}
}
